### ISSUE TITLE
Rearrange config tab contents

### ISSUE THREAD

**Issue by hansu** [fsmMLK/inkscapeDimensions#12]
What do you think of rearranging the config tab contents?

Now:

**Config:**
  - Text color 
  - Line color 

**Style**
- Linear dimension marker style
- Marker sizes ...

My suggestion:

**Style:**
  - Text color 
  - Line color 
- Linear dimension marker style

**Sizes**
- Marker sizes ...

Would then look something iike this way:

![Screenshot_2021-04-24_10-30-46](https://user-images.githubusercontent.com/67957916/115952982-524c4f00-a4e9-11eb-9105-4b65050e3be9.png)

![Screenshot_2021-04-24_10-31-00](https://user-images.githubusercontent.com/67957916/115952984-54aea900-a4e9-11eb-8603-db7fb5235ed9.png)

**Comment by fsmMLK** [comment]
I will take a look.

**Comment by fsmMLK** [comment]
done! Thanks!
