### ISSUE TITLE
Arrow length

### ISSUE THREAD

**Issue by hansu** [fsmMLK/inkscapeDimensions#13]
How do you managed this that the horizontal line is always as long as your text? Or is that only possible if using Latex?

<img src="https://raw.githubusercontent.com/fsmMLK/inkscapeDimensions/master/docs/images/ANOT_scale.png" width="400" >

If I do that it looks like this:

![Screenshot_2021-04-24_10-44-40](https://user-images.githubusercontent.com/67957916/115953296-e5d24f80-a4ea-11eb-9c24-b6271d324228.png)
or 
![Screenshot_2021-04-24_10-45-04](https://user-images.githubusercontent.com/67957916/115953297-e66ae600-a4ea-11eb-8ef7-53481c45def3.png)

Maybe an option would be to right align the text as it is a common method I think:

![Screenshot_2021-04-24_10-45-26](https://user-images.githubusercontent.com/67957916/115953298-e66ae600-a4ea-11eb-823e-8015e7068ede.png)

What do you think about that?

**Comment by fsmMLK** [comment]
Inkscape does not provide any way (that I am aware) of knowing where text elements end. Therefore I don't know how much I have to extend/cut the line below text. However I can do it with latex elements. =S

**Comment by hansu** [comment]
I mean to let the line length as it is, only adjust the text.
I could imagine set the anchor point to the right and right align the text.

**Comment by fsmMLK** [comment]
yes, it is possible to do that, but the problem persists because you might still have a shorter (or longer) horizontal line segment under the text.

**Comment by hansu** [comment]
Yes the user has to adjust the line segment length that it has at least the text length. In this case i would think right align is the better choice.
if the text is longer than the line segment, a left align would look better.
As there are no configuration points in this tab yet, i think we can safely add an option to switch between right and left aligning.

**Comment by fsmMLK** [comment]
I might just found one very finicky way of getting length information from text elements. I will investigate it ASAP.

**Comment by hansu** [comment]
Unfortunately this removes the arrow for me:

![Peek 2022-08-09 13-16](https://user-images.githubusercontent.com/67957916/183634695-0c8f2d1b-db04-44f9-8f62-2f3b9e6e27d4.gif)
