### ISSUE TITLE
 Error using inkscapeDimensions extension

### ISSUE THREAD

**Issue by Fordtman** [fsmMLK/inkscapeDimensions#14]
MY APOLOGIES, I HAVE SOLVED THIS "PROBLEM" .... IT WAS A NEW USER PROBLEM. I COULD NOT FIND A WAY OF DELETING THE ISSUE, HENCE THIS NOTE.

Excellent Extension, well done.

I have just installed the latest version of Inkscape (inkscape-1.1-x64.exe), InkscapeDimensions (inkscapeDimensions-master 1.0), Miktex (basic-miktex-21.6-x64.exe), LaTex. TexText (TexText-Windows-1.4.0.exe) on Windows 10 and ran into the following error when trying to use the installed dimensions extension (see attachments). Any help would be appreciated. NOTE I am a beginner trying to install extensions and get them working.

Inkscape Extensions folder structure after installation of all components (installed in C:\Users\xxx\AppData\Roaming\inkscape\extensions)

┣━extensions
                        ┣━━ inkscapeMadeEasy                              <-- inkscapeMadeEasy folder
                        ┃            ┣━━ inkscapeMadeEasy_Base.py
                        ┃                      ┣━━ inkscapeMadeEasy_Draw.py
                        ┃                      ┣━━ inkscapeMadeEasy_Plot.py
                        ┃                      ┗━━ basicLatexPackages.tex
                        ┃                      ┣━━_pycache_
                         |                                               ┣━━ inkscapeMadeEasy_Base.cpython-38.pyc
                         |                                               ┗━━ inkscapeMadeEasy_Draw.cpython-38.pyc
                         |
                        ┣━━ textext                                                      <-- textext folder
                         |
                        ┣━━ dimensions                                             <--dimensions folder
                        ┃                      ┣━━ dimensions.inx
                        ┃                      ┗━━ dimensions.py

![Dimensions error](https://user-images.githubusercontent.com/18300084/125148748-c6f16a00-e177-11eb-830b-3c658ba8b383.PNG)
![dimensions extension](https://user-images.githubusercontent.com/18300084/125148755-d07ad200-e177-11eb-8fe9-3f7b3f340c00.PNG)

**Comment by fsmMLK** [comment]
Actually you have found a small bug in my code. I just uploaded a new version. Thanks

**Comment by Fordtman** [comment]
Thank you @fsmMLK. As a newbee I am quite apt at finding bugs because most of the time I do not know what I am doing. I'll try harder to do things the right way so I don't uncover bugs that affect 1 in a million. Hope you are keeping well during these uncertain times.
