### ISSUE TITLE
Gigantic dimensions

### ISSUE THREAD

**Issue by ghost** [fsmMLK/inkscapeDimensions#15]
I am using Inkscape 1.1.1 under Linux Mint 20.2 Cinnamon. I just installed dimensions.

I drew a line and opened the dimensions extension. This is what I get:

![image](https://user-images.githubusercontent.com/56895621/138011025-58047f56-e86a-42ef-8585-fba57c46abec.png)

How do I get something more reasonable?

**Comment by fsmMLK** [comment]
I need to see your document properties. Usually this problem happens when the user changes the 'unit per user unit'.
