### ISSUE TITLE
Error using angular dimension, message using linear 

### ISSUE THREAD

**Issue by huanmario7** [fsmMLK/inkscapeDimensions#18]
Started getting this error while trying to apply angular dimension

`Traceback (most recent call last):
  File "C:\Users\buszt\AppData\Roaming\inkscape\extensions\inkscapeDimensions\dimensions.py", line 896, in <module>
    dimension.run()
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\base.py", line 231, in run
    self.save_raw(self.effect())
  File "C:\Users\buszt\AppData\Roaming\inkscape\extensions\inkscapeDimensions\dimensions.py", line 246, in effect
    self.drawAngDim(root_layer, element, label='Dim', invertAngle=so.ANGinvertAngle, textType=so.AngContents_subtab,
  File "C:\Users\buszt\AppData\Roaming\inkscape\extensions\inkscapeDimensions\dimensions.py", line 334, in drawAngDim
    if auxElemType == '3points':
UnboundLocalError: local variable 'auxElemType' referenced before assignment`

Also this message while using linear dimension, though it creates the dimension
`<frozen importlib._bootstrap>:671: ImportWarning: DynamicImporter.exec_module() not found; falling back to load_module()
<frozen importlib._bootstrap>:671: ImportWarning: DynamicImporter.exec_module() not found; falling back to load_module()
C:\Users\buszt\AppData\Roaming\inkscape\extensions\textext\base.py:415: DeprecationWarning: inkex.deprecated.main.transform_imul -> Use @= operator instead
  full_layer_transform *= layer.transform
C:\Users\buszt\AppData\Roaming\inkscape\extensions\textext\base.py:419: DeprecationWarning: inkex.deprecated.main.transform_mul -> Use @ operator instead
  tt_node.transform = (-full_layer_transform *               # map to view coordinate system`

**Comment by fsmMLK** [comment]
The first error appears when your line segment contains a number of vertices different than 3 or 4.

The second warning is related to textext extension. I have no control over it, but you can manually fix that by going to base.py, line  419 and replace tt.node.transform = ( [LOTS of ARGUMENTS ])
 by 
 
                     tt_node.transform = (-full_layer_transform @               # map to view coordinate system
                                         Transform(translate=view_center) @    # place at view center
                                         Transform(scale=user_scale_factor) @  # scale
                                         Transform(translate=-node_center) @   # place node at origin
                                         tt_node.transform                     # use original node transform
                                         )
