### ISSUE TITLE
Displaced dimension

### ISSUE THREAD

**Issue by pgilfernandez** [fsmMLK/inkscapeDimensions#2]
Everytime I create a dimension it's not placed correctly but shifted:
<img width="1014" alt="screenshot" src="https://user-images.githubusercontent.com/5942369/46951840-69449780-d089-11e8-95d0-207c664bc36f.png">
Any idea?

Thanks

**Comment by fsmMLK** [comment]
I just identified the issue. I am working on it.

This issue occurs if you create the placeholder line inside a group that has been transformed (moved/rotated/etc). By default, the extension will create the new elements in the root layer, outside the current active group and, therefore, will not take the transformation into account.

A temporary workaround is to go back to root layer (double click outside the group) before creating the placeholder line.

Please check if this will fix your issue and report back.

Cheers.

**Comment by pgilfernandez** [comment]
Hi,

Umm, I'm not using any group, I just open Inkscape, create a line and then run your script... maybe in macOS it introduces this displacement because other reason...
I'll test your fix, thanks

Cheers

**Comment by DOSull** [comment]
I am also seeing this problem. When I make a new element and dimension it immediately, the annotation appears in the correct place, as I would expect. If I have moved the element from where it was when first created, then the dimension shows up in the wrong place.

**Comment by fsmMLK** [comment]
Please check whether you are within a group other than root. I am still working in a solution for that. The issue is that in many situations you do want to have this odd behaviour.
