### ISSUE TITLE
Extension is greyed out in Inkscape 1.3.2

### ISSUE THREAD

**Issue by rustbuckett** [fsmMLK/inkscapeDimensions#21]
I'm trying to install and use this extension in Inkscape 1.3.2 on Windows 11. Python 3.12 is installed and working. I went through the manual installation process, installing LaTeX and TexText, and copying the files for inkscapeMadeEasy and inkscapeDimensions to the extensions directory. When I open a file in Inkscape and try to select the extension, it is greyed out in the menu. Does this extension still work in the newest versions of Inkscape?

**Comment by fsmMLK** [comment]
I will investigate. It should work.

**Comment by fsmMLK** [comment]
Usually this problem happens when something is not loaded correctly. Did you install from the 'latest' folder?

**Comment by rustbuckett** [comment]
I thought I had pulled the files from 'latest', but I did it again and now I can select the extension. When I try to use it, I get the error:

```
Traceback (most recent call last):
  File "C:\Users\rssti\AppData\Roaming\inkscape\extensions\dimensions\dimensions.py", line 10, in <module>
    import inkscapeMadeEasy.inkscapeMadeEasy_Draw as inkDraw
  File "C:\Users\rssti\AppData\Roaming\inkscape\extensions\inkscapeMadeEasy\inkscapeMadeEasy_Draw.py", line 44, in <module>
    import textextLib.textext as textext
ModuleNotFoundError: No module named 'textextLib'
```

Since the original issue is solved, I can open a new issue if you'd like.

**Comment by fsmMLK** [comment]
You have to install the 'latest' version of inkscapeMadeEasy too. This erros appear when you try runnin v. 0.9x

**Comment by rustbuckett** [comment]
That did it. Thank you for your help and patience.
