### ISSUE TITLE
Dimensions instance has no attribute 'userUnit2unit'

### ISSUE THREAD

**Issue by DOSull** [fsmMLK/inkscapeDimensions#3]
This is a really great project!

Ubuntu 18.0.4; Inkscape 0.92.3

I am getting the following error report when I attempt to add a linear dimension

```
Traceback (most recent call last):
  File "dimensions.py", line 838, in <module>
    dimension.affect()
  File "/usr/share/inkscape/extensions/inkex.py", line 283, in affect
    self.effect()
  File "dimensions.py", line 202, in effect
    horizontalText=so.LINhorizontalText,invertTextSide=so.LINinvertTextSide,smallDimension=so.LINsmalDimStyle)
  File "dimensions.py", line 603, in drawLinDim
    value=self.userUnit2unit(value,self.documentUnit)
AttributeError: Dimensions instance has no attribute 'userUnit2unit'
```
When I run it with 'Custom' set I get a dimensional arrow with 'value' on it, so I think I have things set up correctly in general (i.e. my installation can access required LaTeX components, etc.)

Probably this is some silly configuration issue, but I can't find any suggestions elsewhere online as to what the possible problem might be.

**Comment by DOSull** [comment]
looks like the function `userUnit2unit()` doesn't exist anywhere in the code, and commenting out line 603 allows things to work?

**Comment by fsmMLK** [comment]
My mistake. Last week I was adding new features to inkscapeDimensions but I Forgot to upload the updated version of inkscapeMadeEasy, compatible with the new features. I will upload it ASAP (Tomorrow probably).

**Comment by fsmMLK** [comment]
I just uploaded a new version of InkscapeMadeEasy containing the missing functions.
