### ISSUE TITLE
Only the pixel values are shown, even if changed to mm in Inkscape

### ISSUE THREAD

**Issue by ufwGE** [fsmMLK/inkscapeDimensions#4]
I'm trying to use the Dimensions extensions, but whenever I want to use e.g. the "mm" value (which is selected in Inkscape) the Dimensions extension is only showing the pixel equivalent.
Example, I've drawn a line with 30.235px, I changed the length indicator to mm witch is exactly 8mm. Then I've added the linear Dimension for this line and got ->30.235<-
BUT I want -> 8 <-   !!!
What may be wrong?  I'm sorry, if I missuse this issue field.

**Comment by fsmMLK** [comment]
Thanks for the feedback.

previously the unit option was purely cosmetic. The unit selection just added the unit symbol. I decided to change it and uploaded a newer version. Now unit selection will affect the value.

Please check whether it shows values you were expecting.

**Comment by ufwGE** [comment]
Now that is perfect for what I need! Thank you very much for your fast reply.
