### ISSUE TITLE
Dimension arrow of the previously created disappears

### ISSUE THREAD

**Issue by cnlinyuan** [fsmMLK/inkscapeDimensions#5]
when I first created a linear linear, everything worked fine. But when I then create a linear dimensions, the dimension arrow of the previously created disappears. 
Can you fix this?
Also, can the annotated arrows be the same as linear linears?
Thanks
![Peek 2019-05-24 20-32](https://user-images.githubusercontent.com/50995265/58337219-e3d36200-7e77-11e9-821c-dc6ede7fa999.gif)

**Comment by fsmMLK** [comment]
I was not able to reproduce this error. Can you upload a svg file saved after the arrows disappeared?

**Comment by cnlinyuan** [comment]
OS: Manjaro 18.0.4 Illyria
Kernel: x86_64 Linux 5.2.0-1-MANJARO
Inkscape 0.92.4 5da689c313, 2019-01-14

This a svg file saved after the arrows disappeared.
Thanks.

[Test.svg.zip](https://github.com/fsmMLK/inkscapeDimensions/files/3227350/Test.svg.zip)

**Comment by cnlinyuan** [comment]
This a svg file saved after the arrows disappeared.
 Thanks.




------------------ 原始邮件 ------------------
发件人: "fsmMLK"<notifications@github.com>;
发送时间: 2019年5月27日(星期一) 凌晨3:36
收件人: "fsmMLK/inkscapeDimensions"<inkscapeDimensions@noreply.github.com>;
抄送: "LY"<339704677@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [fsmMLK/inkscapeDimensions] Dimension arrow of the previouslycreated disappears (#5)




I was not able to reproduce this error. Can you upload a svg file saved after the arrows disappeared?

**Comment by fsmMLK** [comment]
When I openned the file I was able to see both arrow correctly rendered. Can you see both dimension arrows when you reopen the file you sent me? It might be a rendering update issue in your machine.

There is one possible quick fix for your issue. Before I commit any changes to github try this:
1-) Open dimensions.py in a text editor and go to line 185-ish
2-) Change 'renameMode = 1' to 'renameMode = 2'
3-) save the file, reopen inkscape and test whether it works properly.

One caveat of this solution is that everytime you create a dimension line, a new marker will be created. I might add the option (overwrite marker definition / create a new one) to the plugin.

**Comment by fsmMLK** [comment]
Concerning the annotation arrow style, I am now working on it. I new version should be commited soon.

**Comment by cnlinyuan** [comment]
> When I openned the file I was able to see both arrow correctly rendered. Can you see both dimension arrows when you reopen the file you sent me? It might be a rendering update issue in your machine.
> 
> There is one possible quick fix for your issue. Before I commit any changes to github try this:
> 1-) Open dimensions.py in a text editor and go to line 185-ish
> 2-) Change 'renameMode = 1' to 'renameMode = 2'
> 3-) save the file, reopen inkscape and test whether it works properly.
> 
> One caveat of this solution is that everytime you create a dimension line, a new marker will be created. I might add the option (overwrite marker definition / create a new one) to the plugin.

**Comment by cnlinyuan** [comment]
When I open the file, I only see one size arrow.I follow the method you gave, it works properly.Thank you very much for your help.Looking forward to the new version coming soon.

**Comment by cnlinyuan** [comment]
> When I openned the file I was able to see both arrow correctly rendered. Can you see both dimension arrows when you reopen the file you sent me? It might be a rendering update issue in your machine.
> 
> There is one possible quick fix for your issue. Before I commit any changes to github try this:
> 1-) Open dimensions.py in a text editor and go to line 185-ish
> 2-) Change 'renameMode = 1' to 'renameMode = 2'
> 3-) save the file, reopen inkscape and test whether it works properly.
> 
> One caveat of this solution is that everytime you create a dimension line, a new marker will be created. I might add the option (overwrite marker definition / create a new one) to the plugin.

When I open the file, I only see one size arrow.I follow the method you gave, it works properly.
