### ISSUE TITLE
unable to draw linear dimensions

### ISSUE THREAD

**Issue by bantaj** [fsmMLK/inkscapeDimensions#7]
I installed the dimensions package with all dependencies and it worked for several days but I am now getting the following error when trying to apply linear dimensions: 

> ValueError: need more than 0 values to unpack

This is a screenshot of the full error:

![image](https://user-images.githubusercontent.com/5356186/73085896-216c0d00-3e95-11ea-8c74-1ab426a94ef6.png)

**Comment by fsmMLK** [comment]
have you tried the newest version?

**Comment by hansu** [comment]
A similiar error on my installation:

```
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
Traceback (most recent call last):
  File "dimensions.py", line 903, in <module>
    dimension.run()
  File "/usr/share/inkscape/extensions/inkex/base.py", line 140, in run
    self.save_raw(self.effect())
  File "dimensions.py", line 258, in effect
    dimPosition=so.ANGdimPosition, dimDistance=so.ANGannotationDistance)
  File "dimensions.py", line 343, in drawAngDim
    if auxElemType == '3points':
UnboundLocalError: local variable 'auxElemType' referenced before assignment
```

Ubuntu 18
Inkscape 1.0.2
Latest version of inkscapeDimensions

**Comment by fsmMLK** [comment]
hansu,

for angular annotations you need a line segment with 3 or 4 points only. check if you have more.

**Comment by hansu** [comment]
Sorry I was in the wrong tab when coping the error message. I wanted a linear dimension. But this fails also:

![Screenshot_2021-04-23_07-45-36](https://user-images.githubusercontent.com/67957916/115824713-a6cbcd80-a408-11eb-86e0-78f931321498.png)
![Screenshot_2021-04-23_07-45-49](https://user-images.githubusercontent.com/67957916/115824727-aa5f5480-a408-11eb-817a-b528f80328f9.png)

**Comment by fsmMLK** [comment]
I uploaded a new version yesterday that should fix this issue. Also check if your inkscapemadeeasy is updated.

**Comment by hansu** [comment]
Very nice, that works.
Thanks!
