### ISSUE TITLE
Can't make it run

### ISSUE THREAD

**Issue by reselty** [fsmMLK/inkscapeDimensions#8]
Hi 
I installed https://github.com/fsmMLK/inkscapeMadeEasy, as I should.

the following files are not in the extension folder after this (as you write in
https://github.com/fsmMLK/inkscapeDimensions) :
    |-- drawAmpOp.py 
            |-- drawArrows.py
            |-- drawDiodes.py
            |-- drawRLC.py
            |-- drawSignals.py
            |-- drawSources.py
            |-- drawSwitches.py
            |-- drawTransistors.py
|-- textextLib
            |   |-- CircuitSymbolsLatexPreamble.tex      <-- add this file to  textextLib  subdirectoy

I receive following message by using extensions>fsmMLK>Dimensions on a sinlge selected path:

C:\Program Files (x86)\Inkscape.48.5-32\share\extensions\textextLib\textext.py:63: DeprecationWarning: the md5 module is deprecated; use hashlib instead
  import os, sys, tempfile, traceback, glob, re, md5, copy
Traceback (most recent call last):
  File "dimensions.py", line 907, in <module>
    dimension.affect()
  File "C:\Program Files (x86)\Inkscape.48.5-32\share\extensions\inkex.py", line 215, in affect
    self.effect()
  File "dimensions.py", line 245, in effect
    invertTextSide=so.LINinvertTextSide, smallDimension=so.LINsmalDimStyle)

  File "dimensions.py", line 822, in drawLinDim
    textColor=self.textColor, LatexCommands=' ', angleDeg=angle)
  File "C:\Program Files (x86)\Inkscape.48.5-32\share\extensions\inkscapeMadeEasy_Draw.py", line 1247, in latex
    tempFilePath], output=False)
  File "C:\Program Files (x86)\Inkscape.48.5-32\share\extensions\inkex.py", line 215, in affect
    self.effect()
  File "C:\Program Files (x86)\Inkscape.48.5-32\share\extensions\textextLib\textext.py", line 125, in effect
    % ';\n'.join(converter_errors))
RuntimeError: No Latex -> SVG converter available:
PstoeditPlotSvg: Command pstoedit -help failed: [Error 2] Das System kann die angegebene Datei nicht finden;
SkConvert: Command pstoedit failed: [Error 2] Das System kann die angegebene Datei nicht finden;
Pdf2Svg: Command pdf2svg failed: [Error 2] Das System kann die angegebene Datei nicht finden

Do I have to install so many other extensions?
Thanks for any help !

**Comment by fsmMLK** [comment]
Have you tried with the newest version? in the past pstoedit was necessary and caused problems to many users. The newest version (for inkscape 1.0) does not need it anymore.

**Comment by reselty** [comment]
Thank you very much for letting me know !
I tried instantly but stoped, when I couldnt find a way to direct TexTex to the portable installation.
I have to use .47 / .48 / 1.0 parallel not one can do everything I need ;-)
So before I install 1.0 parallel to a installed .48 I'll try potable ways - if you know the path would be great to let me know !
Sincerely Reselty
